baseURL = 'https://daddy-ananta.vercel.app/'
languageCode = 'id-ID'
defaultContentLanguage = "id"
defaultContentLang = "id"
title = 'Daddy Ananta'
enableRobotsTXT = true
tableOfContents = true

pagination.pagerSize = 8

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1


[params]
    description = "Saya Daddy Ananta seorang Data Analyst dengan ketertarikan mendalam pada analisis data dan visualisasi. Saya memiliki kemampuan dalam mengolah data untuk menemukan pola, tren, serta insight yang dapat membantu pengambilan keputusan strategis. Dengan pendekatan berbasis data, saya tidak hanya sekadar menyajikan angka, tetapi juga menerjemahkannya menjadi visualisasi yang informatif dan mudah dipahami. Saya percaya bahwa setiap data memiliki cerita di baliknya, dan tugas saya adalah mengungkap wawasan berharga yang dapat mendorong pertumbuhan bisnis serta inovasi."
    dateFormat= "2 January 2006"
    goatcounter = "lamtiarsigiro"
    math = true
    ShowPageViews = true

[params.social.share]
    facebook = true
    linkedin = true
    twitter = true
    whatsapp = true
    email = true

[taxonomies]
    category = "categories"
    author = "authors"
    tag = "tags"

[markup.goldmark.renderer]
  unsafe = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  
  [markup.tableOfContents]
    startLevel = 1
    ordered = false
    endLevel = 4

[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML"]

[outputFormats.HTML]
  mediaType = "text/html"
  baseName = "index"
  isPlainText = false
  rel = "canonical"
  noUglyURLs = true
  gzip = true
  minify = true
  [[outputFormats.HTML.headers]]
        cache-control = "public, max-age=7200, no-cache, must-revalidate" # 2 jam, dengan validasi
    
[outputFormats.CSS]
    mediaType = "text/css"
    baseName = "style"
    isPlainText = false
    gzip = true
    minify = true
    [[outputFormats.CSS.headers]]
        cache-control = "public, max-age=31536000, immutable" # 1 Tahun untuk CSS

