<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>XML Sitemap Index</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style type="text/css">
            /* --- Reset & Basic Setup --- */
            body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                margin: 0;
                background-color: #f7fafc; /* Latar belakang abu-abu sangat muda */
                color: #4a5568; /* Warna teks utama lebih lembut dari hitam */
            }
            a {
                color: #2563eb; /* Warna biru modern untuk link */
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }

            /* --- Main Container --- */
            .container {
                max-width: 960px;
                margin: 2rem auto;
                padding: 1rem;
            }

            /* --- Header --- */
            .header {
                padding: 1.5rem;
                background-color: #ffffff;
                border-bottom: 1px solid #e2e8f0;
                border-radius: 8px 8px 0 0;
            }
            h1 {
                font-size: 1.75rem;
                font-weight: 600;
                margin: 0;
                color: #1a202c;
            }
            .header p {
                margin: 0.5rem 0 0;
                color: #718096;
                font-size: 0.9rem;
            }
            
            /* --- Table Styling --- */
            .sitemap-table {
                width: 100%;
                background-color: #ffffff;
                border-collapse: collapse;
                box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
                border-radius: 0 0 8px 8px;
            }
            th, td {
                padding: 1rem 1.5rem;
                text-align: left;
                border-bottom: 1px solid #e2e8f0;
            }
            th {
                font-size: 0.75rem;
                font-weight: 600;
                color: #718096;
                text-transform: uppercase;
                letter-spacing: 0.05em;
                background-color: #f7fafc;
            }
            tbody tr:hover {
                background-color: #f7fafc; /* Efek hover pada baris */
            }
            tbody tr:last-child td {
                border-bottom: none;
            }
            td a {
                font-weight: 500;
            }

            /* --- Footer --- */
            .footer {
                text-align: center;
                margin-top: 1.5rem;
                font-size: 0.85rem;
                color: #a0aec0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>XML Sitemap Index</h1>
                <p>Ini adalah "daftar isi" untuk semua peta situs yang ada. Setiap link di bawah ini mengarah ke peta situs yang lebih spesifik.</p>
            </div>
            <table class="sitemap-table">
                <thead>
                    <tr>
                        <th>Lokasi Peta Situs</th>
                        <th style="width:25%;">Terakhir Diperbarui</th>
                    </tr>
                </thead>
                <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                    <tr>
                        <td>
                            <xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                            <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                        </td>
                        <td>
                            <xsl:value-of select="concat(substring(sitemap:lastmod,0,11), ' ', substring(sitemap:lastmod,12,8))"/>
                        </td>
                    </tr>
                </xsl:for-each>
                </tbody>
            </table>
            <div class="footer">
                <p>Generated by Hugo</p>
            </div>
        </div>
    </body>
    </html>
</xsl:template>
</xsl:stylesheet>