name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: sudo apt-get install hugo -y

      - name: Build site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: daddyananta/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
